services:
  app:
    build: .
    container_name: go_backend_app
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Chỉ chạy App khi DB đã HEALTHY
    environment:
      - APP_PORT=:8080
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ahihi_db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: go_backend_db
    cap_add:
      - SYS_NICE # Tránh warning của MySQL 8 trên Docker
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ahihi_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-psecret",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network
    # --- THÊM DÒNG LỆNH NÀY ---
    # Bật tính năng nhận dữ liệu từ bên ngoài (k6)
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --storage.tsdb.path=/prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    restart: always
    volumes:
      # SỬA DÒNG NÀY: Mount vào /etc thay vì /root
      - ./my.cnf:/etc/.my.cnf
    command:
      # SỬA DÒNG NÀY: Trỏ config vào đường dẫn mới
      - "--config.my-cnf=/etc/.my.cnf"
      - "--mysqld.address=db:3306"
    ports:
      - "9104:9104"
    networks:
      - app_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
